package com.cmc.utxo.etp.mapper;

import com.cmc.utxo.etp.model.po.MvsUtxo;

import java.util.ArrayList;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MvsUtxoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MVS_UTXO
     *
     * @mbggenerated Thu Sep 13 10:53:27 CST 2018
     */
    int deleteByPrimaryKey(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MVS_UTXO
     *
     * @mbggenerated Thu Sep 13 10:53:27 CST 2018
     */
    int insert(MvsUtxo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MVS_UTXO
     *
     * @mbggenerated Thu Sep 13 10:53:27 CST 2018
     */
    int insertSelective(MvsUtxo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MVS_UTXO
     *
     * @mbggenerated Thu Sep 13 10:53:27 CST 2018
     */
    MvsUtxo selectByPrimaryKey(int id);

    MvsUtxo selectByHashAndIndex(@Param("hash")String hash,@Param("index")String index);
    
    
    ArrayList<MvsUtxo> selectByAddress(@Param("address")String address,@Param("symbol")String symbol,@Param("isUsed")Integer[] isUsed);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MVS_UTXO
     *
     * @mbggenerated Thu Sep 13 10:53:27 CST 2018
     */
    int updateByPrimaryKeySelective(MvsUtxo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MVS_UTXO
     *
     * @mbggenerated Thu Sep 13 10:53:27 CST 2018
     */
    int updateByPrimaryKey(MvsUtxo record);
}