package com.cmc.utxo.etp.mapper;

import com.cmc.utxo.etp.model.po.TokenUnit;

public interface TokenUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKEN_ADDRESS
     *
     * @mbggenerated Mon Sep 17 16:51:26 CST 2018
     */
    int insert(TokenUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TOKEN_ADDRESS
     *
     * @mbggenerated Mon Sep 17 16:51:26 CST 2018
     */
    int insertSelective(TokenUnit record);
    
    
    TokenUnit selectBySymbol(String symbol);
}